###
# @name login
POST https://localhost:9000/api/users/login
Content-Type: application/json

{
  "email": "Tutor@avancira.com",
  "password": "Test@1234"
}

### Get categories using the token
GET https://localhost:9000/api/lesson/categories
Authorization: Bearer {{login.response.body.token}}
Accept: application/json


### Get categories using the token
GET https://localhost:9000/api/listings/-1211748162
Accept: application/json
