namespace Avancira.Infrastructure.Configuration;

public record AppEnvironment(
    string DatabaseHost,
    string DatabasePort,
    string DatabaseName,
    string DatabaseUser,
    string DatabasePassword,
    string AuthIssuer,
    string JwtAudience,
    string JwtIssuer,
    string JwtKey,
    string AppBaseUrl,
    string AppFrontEndUrl,
    string AppName,
    string AppSupportEmail,
    string AppSupportPhone,
    string GoogleClientId,
    string GoogleClientSecret,
    string FacebookAppId,
    string FacebookAppSecret,
    string SmtpHost,
    string SmtpPort,
    string EmailFrom,
    string EmailFromName,
    string SendGridApiKey,
    string TwilioAccountSid,
    string TwilioAuthToken,
    string TwilioPhoneNumber,
    string GraphApiClientId,
    string GraphApiClientSecret,
    string GraphApiTenantId,
    string StripeApiKey,
    string StripePublishableKey,
    string StripeSecretKey,
    string PaypalClientId,
    string PaypalClientSecret,
    string PaypalEnvironment,
    string JitsiAppId,
    string JitsiAppSecret,
    string JitsiDomain
)
{
    public IDictionary<string, string> ToDictionary() => new Dictionary<string, string>
    {
        { "Avancira__Database__Host", DatabaseHost },
        { "Avancira__Database__Port", DatabasePort },
        { "Avancira__Database__Name", DatabaseName },
        { "Avancira__Database__User", DatabaseUser },
        { "Avancira__Database__Password", DatabasePassword },
        { "Avancira__Auth__Issuer", AuthIssuer },
        { "Auth__Issuer", AuthIssuer },
        { "Avancira__Jwt__Audience", JwtAudience },
        { "Avancira__Jwt__Issuer", JwtIssuer },
        { "Avancira__Jwt__Key", JwtKey },
        { "Avancira__App__BaseUrl", AppBaseUrl },
        { "Avancira__App__FrontEndUrl", AppFrontEndUrl },
        { "Avancira__App__Name", AppName },
        { "Avancira__App__SupportEmail", AppSupportEmail },
        { "Avancira__App__SupportPhone", AppSupportPhone },
        { "Avancira__ExternalServices__Google__ClientId", GoogleClientId },
        { "Avancira__ExternalServices__Google__ClientSecret", GoogleClientSecret },
        { "Avancira__ExternalServices__Facebook__AppId", FacebookAppId },
        { "Avancira__ExternalServices__Facebook__AppSecret", FacebookAppSecret },
        { "Avancira__Notifications__Smtp__Host", SmtpHost },
        { "Avancira__Notifications__Smtp__Port", SmtpPort },
        { "Avancira__Notifications__Email__From", EmailFrom },
        { "Avancira__Notifications__Email__FromName", EmailFromName },
        { "Avancira__Notifications__SendGrid__ApiKey", SendGridApiKey },
        { "Avancira__Notifications__Twilio__AccountSid", TwilioAccountSid },
        { "Avancira__Notifications__Twilio__AuthToken", TwilioAuthToken },
        { "Avancira__Notifications__Twilio__PhoneNumber", TwilioPhoneNumber },
        { "Avancira__Notifications__GraphApi__ClientId", GraphApiClientId },
        { "Avancira__Notifications__GraphApi__ClientSecret", GraphApiClientSecret },
        { "Avancira__Notifications__GraphApi__TenantId", GraphApiTenantId },
        { "Avancira__Payments__Stripe__ApiKey", StripeApiKey },
        { "Avancira__Payments__Stripe__PublishableKey", StripePublishableKey },
        { "Avancira__Payments__Stripe__SecretKey", StripeSecretKey },
        { "Avancira__Payments__Paypal__ClientId", PaypalClientId },
        { "Avancira__Payments__Paypal__ClientSecret", PaypalClientSecret },
        { "Avancira__Payments__Paypal__Environment", PaypalEnvironment },
        { "Avancira__Jitsi__AppId", JitsiAppId },
        { "Avancira__Jitsi__AppSecret", JitsiAppSecret },
        { "Avancira__Jitsi__Domain", JitsiDomain }
    };
}
