name: Frontend - Angular

on:
  push:
    branches:
      - master
      - themeforest-template
  pull_request:
    branches:
      - master
      - themeforest-template

jobs:

  build-docker:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    # Build and push frontend Docker image
    - name: Build and push frontend Docker image
      run: |
        docker build -t "mirotivo/avancira-frontend:latest" ./Frontend.Angular
        docker push "mirotivo/avancira-frontend:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:    
    # SSH into the server and deploy the frontend container
    - name: Deploy frontend to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker pull mirotivo/avancira-frontend:latest
          docker stop avancira-frontend-container || true
          docker rm avancira-frontend-container || true
          docker run -d -p 8000:80 --name avancira-frontend-container mirotivo/avancira-frontend:latest
